// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NutritionPlanner.DataAccess;

#nullable disable

namespace NutritionPlanner.DataAccess.Migrations
{
    [DbContext(typeof(NutritionPlannerDbContext))]
    [Migration("20250608172338_addReicpes")]
    partial class addReicpes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NutritionPlanner.DataAccess.Entities.ActivityLevelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Coefficient")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ActivityLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Coefficient = 1.2,
                            Description = "Офисная работа, минимальная физическая активность.",
                            Name = "Сидячий"
                        },
                        new
                        {
                            Id = 2,
                            Coefficient = 1.375,
                            Description = "Легкая физическая нагрузка или занятия спортом 1-3 раза в неделю.",
                            Name = "Маленькая активность"
                        },
                        new
                        {
                            Id = 3,
                            Coefficient = 1.55,
                            Description = "Занятия спортом 3-5 раз в неделю.",
                            Name = "Умеренная активность"
                        },
                        new
                        {
                            Id = 4,
                            Coefficient = 1.7250000000000001,
                            Description = "Интенсивные занятия спортом 6-7 раз в неделю.",
                            Name = "Высокая активность"
                        },
                        new
                        {
                            Id = 5,
                            Coefficient = 1.8999999999999999,
                            Description = "Ежедневные интенсивные тренировки или физическая работа.",
                            Name = "Экстремальная активность"
                        });
                });

            modelBuilder.Entity("NutritionPlanner.DataAccess.Entities.ChatMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("NutritionPlanner.DataAccess.Entities.GoalTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GoalTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Снижение веса за счет дефицита калорий.",
                            Name = "Похудение"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Увеличение мышечной массы за счет профицита калорий.",
                            Name = "Набор массы"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Стабилизация текущего веса.",
                            Name = "Поддержание веса"
                        });
                });

            modelBuilder.Entity("NutritionPlanner.DataAccess.Entities.MealPlanEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalCalories")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalCarbohydrates")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalFat")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalProtein")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("NutritionPlanner.DataAccess.Entities.MealPlanItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int?>("MealPlanEntityId")
                        .HasColumnType("integer");

                    b.Property<int>("MealPlanId")
                        .HasColumnType("integer");

                    b.Property<int>("MealTimeId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanEntityId");

                    b.ToTable("MealPlanItems");
                });

            modelBuilder.Entity("NutritionPlanner.DataAccess.Entities.MealTimeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MealTimes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Первый прием пищи в начале дня.",
                            Name = "Завтрак"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Основной прием пищи днем.",
                            Name = "Обед"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Прием пищи в конце дня.",
                            Name = "Ужин"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Легкий промежуточный прием пищи.",
                            Name = "Перекус"
                        });
                });

            modelBuilder.Entity("NutritionPlanner.DataAccess.Entities.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Calories")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Carbohydrates")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Fat")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Protein")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 77m,
                            Carbohydrates = 0.3m,
                            Fat = 5.6m,
                            IsApproved = true,
                            Name = "Яйцо куринное",
                            Protein = 6.2m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 2,
                            Calories = 160m,
                            Carbohydrates = 8.5m,
                            Fat = 14.7m,
                            IsApproved = true,
                            Name = "Авокадо",
                            Protein = 2.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 3,
                            Calories = 70m,
                            Carbohydrates = 13.0m,
                            Fat = 0.5m,
                            IsApproved = true,
                            Name = "Хлеб цельнозерновой",
                            Protein = 3.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 4,
                            Calories = 579m,
                            Carbohydrates = 21.6m,
                            Fat = 49.9m,
                            IsApproved = true,
                            Name = "Миндаль",
                            Protein = 21.2m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 5,
                            Calories = 52m,
                            Carbohydrates = 14.0m,
                            Fat = 0.2m,
                            IsApproved = true,
                            Name = "Яблоко",
                            Protein = 0.3m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 6,
                            Calories = 165m,
                            Carbohydrates = 0.0m,
                            Fat = 3.6m,
                            IsApproved = true,
                            Name = "Грудка куриная",
                            Protein = 31.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 7,
                            Calories = 35m,
                            Carbohydrates = 6.6m,
                            Fat = 0.4m,
                            IsApproved = true,
                            Name = "Брокколи",
                            Protein = 3.7m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 8,
                            Calories = 654m,
                            Carbohydrates = 13.7m,
                            Fat = 65.2m,
                            IsApproved = true,
                            Name = "Грецкие орехи",
                            Protein = 15.2m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 9,
                            Calories = 89m,
                            Carbohydrates = 22.8m,
                            Fat = 0.3m,
                            IsApproved = true,
                            Name = "Банан",
                            Protein = 1.1m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 10,
                            Calories = 190m,
                            Carbohydrates = 9.0m,
                            Fat = 2.0m,
                            IsApproved = true,
                            Name = "Протеиновый коктейль",
                            Protein = 30.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 11,
                            Calories = 96m,
                            Carbohydrates = 3.0m,
                            Fat = 5.0m,
                            IsApproved = true,
                            Name = "Творог 5%",
                            Protein = 10.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 12,
                            Calories = 304m,
                            Carbohydrates = 82.4m,
                            Fat = 0.0m,
                            IsApproved = true,
                            Name = "Мед",
                            Protein = 0.3m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 13,
                            Calories = 50m,
                            Carbohydrates = 12.0m,
                            Fat = 0.3m,
                            IsApproved = true,
                            Name = "Ягоды",
                            Protein = 1.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 14,
                            Calories = 182m,
                            Carbohydrates = 0.0m,
                            Fat = 12.0m,
                            IsApproved = true,
                            Name = "Лосось",
                            Protein = 20.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 15,
                            Calories = 80m,
                            Carbohydrates = 17.0m,
                            Fat = 0.1m,
                            IsApproved = true,
                            Name = "Картофель запеченный",
                            Protein = 2.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 16,
                            Calories = 389m,
                            Carbohydrates = 66.3m,
                            Fat = 6.9m,
                            IsApproved = true,
                            Name = "Овсянка",
                            Protein = 16.9m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 17,
                            Calories = 50m,
                            Carbohydrates = 4.8m,
                            Fat = 1.5m,
                            IsApproved = true,
                            Name = "Молоко 1.5%",
                            Protein = 3.3m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 18,
                            Calories = 41m,
                            Carbohydrates = 9.0m,
                            Fat = 0.4m,
                            IsApproved = true,
                            Name = "Киви",
                            Protein = 0.9m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 19,
                            Calories = 120m,
                            Carbohydrates = 21.3m,
                            Fat = 1.9m,
                            IsApproved = true,
                            Name = "Киноа",
                            Protein = 4.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 20,
                            Calories = 158m,
                            Carbohydrates = 0.0m,
                            Fat = 5.0m,
                            IsApproved = true,
                            Name = "Индейка",
                            Protein = 29.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 21,
                            Calories = 16m,
                            Carbohydrates = 3.1m,
                            Fat = 0.1m,
                            IsApproved = true,
                            Name = "Кабачки",
                            Protein = 1.2m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 22,
                            Calories = 150m,
                            Carbohydrates = 0.0m,
                            Fat = 7.0m,
                            IsApproved = true,
                            Name = "Говядина тушеная",
                            Protein = 20.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 23,
                            Calories = 130m,
                            Carbohydrates = 28.2m,
                            Fat = 0.3m,
                            IsApproved = true,
                            Name = "Рис белый",
                            Protein = 2.7m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 24,
                            Calories = 343m,
                            Carbohydrates = 57.5m,
                            Fat = 3.3m,
                            IsApproved = true,
                            Name = "Гречка",
                            Protein = 13.3m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 25,
                            Calories = 342m,
                            Carbohydrates = 74.0m,
                            Fat = 1.5m,
                            IsApproved = true,
                            Name = "Булгур",
                            Protein = 12.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 26,
                            Calories = 82m,
                            Carbohydrates = 0.0m,
                            Fat = 0.7m,
                            IsApproved = true,
                            Name = "Треска",
                            Protein = 18.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 27,
                            Calories = 23m,
                            Carbohydrates = 3.6m,
                            Fat = 0.4m,
                            IsApproved = true,
                            Name = "Шпинат",
                            Protein = 2.9m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 28,
                            Calories = 57m,
                            Carbohydrates = 15.0m,
                            Fat = 0.1m,
                            IsApproved = true,
                            Name = "Груша",
                            Protein = 0.4m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 29,
                            Calories = 553m,
                            Carbohydrates = 30.2m,
                            Fat = 43.8m,
                            IsApproved = true,
                            Name = "Кешью",
                            Protein = 18.2m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 30,
                            Calories = 111m,
                            Carbohydrates = 23.0m,
                            Fat = 0.9m,
                            IsApproved = true,
                            Name = "Рис бурый",
                            Protein = 2.6m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 31,
                            Calories = 90m,
                            Carbohydrates = 0.0m,
                            Fat = 10.0m,
                            IsApproved = true,
                            Name = "Оливковое масло",
                            Protein = 0.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 32,
                            Calories = 150m,
                            Carbohydrates = 3.0m,
                            Fat = 9.0m,
                            IsApproved = true,
                            Name = "Рикотта",
                            Protein = 11.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 33,
                            Calories = 60m,
                            Carbohydrates = 4.0m,
                            Fat = 1.0m,
                            IsApproved = true,
                            Name = "Греческий йогурт",
                            Protein = 10.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 34,
                            Calories = 150m,
                            Carbohydrates = 12.0m,
                            Fat = 8.0m,
                            IsApproved = true,
                            Name = "Хумус",
                            Protein = 6.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 35,
                            Calories = 280m,
                            Carbohydrates = 0.0m,
                            Fat = 18.0m,
                            IsApproved = true,
                            Name = "Стейк говяжий",
                            Protein = 26.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 36,
                            Calories = 150m,
                            Carbohydrates = 0.0m,
                            Fat = 1.0m,
                            IsApproved = true,
                            Name = "Тунец консервированный",
                            Protein = 26.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 37,
                            Calories = 22m,
                            Carbohydrates = 4.0m,
                            Fat = 0m,
                            IsApproved = true,
                            Name = "Огурец",
                            Protein = 1.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 38,
                            Calories = 20m,
                            Carbohydrates = 4.0m,
                            Fat = 0m,
                            IsApproved = true,
                            Name = "Помидоры черри",
                            Protein = 1.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 39,
                            Calories = 47m,
                            Carbohydrates = 11.8m,
                            Fat = 0.1m,
                            IsApproved = true,
                            Name = "Апельсин",
                            Protein = 0.9m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 40,
                            Calories = 41m,
                            Carbohydrates = 9.6m,
                            Fat = 0.2m,
                            IsApproved = true,
                            Name = "Морковь",
                            Protein = 0.9m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 41,
                            Calories = 579m,
                            Carbohydrates = 21.6m,
                            Fat = 49.9m,
                            IsApproved = true,
                            Name = "Миндаль",
                            Protein = 21.2m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 42,
                            Calories = 31m,
                            Carbohydrates = 7.0m,
                            Fat = 0.1m,
                            IsApproved = true,
                            Name = "Зеленая фасоль",
                            Protein = 2.4m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 43,
                            Calories = 25m,
                            Carbohydrates = 6.0m,
                            Fat = 0.0m,
                            IsApproved = true,
                            Name = "Черника",
                            Protein = 0.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 44,
                            Calories = 82m,
                            Carbohydrates = 0.0m,
                            Fat = 0.7m,
                            IsApproved = true,
                            Name = "Филе трески",
                            Protein = 18.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 45,
                            Calories = 27m,
                            Carbohydrates = 3.3m,
                            Fat = 0.3m,
                            IsApproved = true,
                            Name = "Шампиньоны",
                            Protein = 3.1m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 46,
                            Calories = 70m,
                            Carbohydrates = 13.0m,
                            Fat = 0.5m,
                            IsApproved = true,
                            Name = "Хлеб цельнозерновой",
                            Protein = 3.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 47,
                            Calories = 20m,
                            Carbohydrates = 4.0m,
                            Fat = 0.0m,
                            IsApproved = true,
                            Name = "Помидор",
                            Protein = 1.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 48,
                            Calories = 60m,
                            Carbohydrates = 15.0m,
                            Fat = 0.0m,
                            IsApproved = true,
                            Name = "Груша",
                            Protein = 0.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 49,
                            Calories = 30m,
                            Carbohydrates = 6.0m,
                            Fat = 0.0m,
                            IsApproved = true,
                            Name = "Кабачки",
                            Protein = 2.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 50,
                            Calories = 90m,
                            Carbohydrates = 4.0m,
                            Fat = 3.0m,
                            IsApproved = true,
                            Name = "Йогурт без сахара",
                            Protein = 10.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 51,
                            Calories = 140m,
                            Carbohydrates = 30.0m,
                            Fat = 2.0m,
                            IsApproved = true,
                            Name = "Хлопья цельнозерновые",
                            Protein = 4.0m,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 52,
                            Barcode = "4607001417255",
                            Calories = 420m,
                            Carbohydrates = 55.0m,
                            Fat = 20.0m,
                            IsApproved = true,
                            Name = "Маффины",
                            Protein = 6.0m,
                            Weight = 100m
                        });
                });

            modelBuilder.Entity("NutritionPlanner.DataAccess.Entities.RecipeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Питательный завтрак с яйцами и авокадо",
                            IsApproved = true,
                            Name = "Омлет с авокадо"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Легкий и полезный обед",
                            IsApproved = true,
                            Name = "Салат с курицей и овощами"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Вегетарианский ужин",
                            IsApproved = true,
                            Name = "Гречневая каша с овощами"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Освежающий перекус",
                            IsApproved = true,
                            Name = "Фруктовый смузи"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Полезный ужин с рыбой",
                            IsApproved = true,
                            Name = "Запеченный лосось с картофелем"
                        });
                });

            modelBuilder.Entity("NutritionPlanner.DataAccess.Entities.RecipeIngredientEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 100m,
                            ProductId = 1,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 50m,
                            ProductId = 2,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 10m,
                            ProductId = 31,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 150m,
                            ProductId = 6,
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Amount = 100m,
                            ProductId = 7,
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 6,
                            Amount = 50m,
                            ProductId = 37,
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Amount = 70m,
                            ProductId = 38,
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 8,
                            Amount = 15m,
                            ProductId = 31,
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 9,
                            Amount = 100m,
                            ProductId = 24,
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 10,
                            Amount = 100m,
                            ProductId = 21,
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 11,
                            Amount = 50m,
                            ProductId = 40,
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 12,
                            Amount = 30m,
                            ProductId = 27,
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 13,
                            Amount = 100m,
                            ProductId = 9,
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 14,
                            Amount = 50m,
                            ProductId = 13,
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 15,
                            Amount = 100m,
                            ProductId = 33,
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 16,
                            Amount = 50m,
                            ProductId = 17,
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 17,
                            Amount = 200m,
                            ProductId = 14,
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 18,
                            Amount = 150m,
                            ProductId = 15,
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 19,
                            Amount = 50m,
                            ProductId = 27,
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 20,
                            Amount = 15m,
                            ProductId = 31,
                            RecipeId = 5
                        });
                });

            modelBuilder.Entity("NutritionPlanner.DataAccess.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActivityLevelId")
                        .HasColumnType("integer");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NutritionPlanner.DataAccess.Entities.UserGoalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Calories")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Carbohydrates")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Fat")
                        .HasColumnType("numeric");

                    b.Property<int>("GoalTypeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Protein")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("UserGoals");
                });

            modelBuilder.Entity("NutritionPlanner.DataAccess.Entities.UserProgressEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("CaloriesConsumed")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CarbohydratesConsumed")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("FatConsumed")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ProteinConsumed")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("WaterConsumed")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("UserProgress");
                });

            modelBuilder.Entity("NutritionPlanner.DataAccess.Entities.WeeklyMenuEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GoalTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("MealTimeId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WeeklyMenus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 2m,
                            DayOfWeek = "Понедельник",
                            GoalTypeId = 1,
                            MealTimeId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 0.5m,
                            DayOfWeek = "Понедельник",
                            GoalTypeId = 1,
                            MealTimeId = 1,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 0.3m,
                            DayOfWeek = "Понедельник",
                            GoalTypeId = 1,
                            MealTimeId = 1,
                            ProductId = 46
                        },
                        new
                        {
                            Id = 4,
                            Amount = 2m,
                            DayOfWeek = "Понедельник",
                            GoalTypeId = 1,
                            MealTimeId = 2,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 5,
                            Amount = 2m,
                            DayOfWeek = "Понедельник",
                            GoalTypeId = 1,
                            MealTimeId = 2,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 6,
                            Amount = 0.1m,
                            DayOfWeek = "Понедельник",
                            GoalTypeId = 1,
                            MealTimeId = 2,
                            ProductId = 31
                        },
                        new
                        {
                            Id = 7,
                            Amount = 1.5m,
                            DayOfWeek = "Понедельник",
                            GoalTypeId = 1,
                            MealTimeId = 3,
                            ProductId = 14
                        },
                        new
                        {
                            Id = 8,
                            Amount = 1.5m,
                            DayOfWeek = "Понедельник",
                            GoalTypeId = 1,
                            MealTimeId = 3,
                            ProductId = 27
                        },
                        new
                        {
                            Id = 9,
                            Amount = 0.2m,
                            DayOfWeek = "Понедельник",
                            GoalTypeId = 1,
                            MealTimeId = 4,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 10,
                            Amount = 1m,
                            DayOfWeek = "Понедельник",
                            GoalTypeId = 1,
                            MealTimeId = 4,
                            ProductId = 33
                        },
                        new
                        {
                            Id = 11,
                            Amount = 0.1m,
                            DayOfWeek = "Понедельник",
                            GoalTypeId = 1,
                            MealTimeId = 4,
                            ProductId = 12
                        },
                        new
                        {
                            Id = 12,
                            Amount = 1.5m,
                            DayOfWeek = "Понедельник",
                            GoalTypeId = 1,
                            MealTimeId = 4,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 13,
                            Amount = 0.4m,
                            DayOfWeek = "Вторник",
                            GoalTypeId = 1,
                            MealTimeId = 1,
                            ProductId = 16
                        },
                        new
                        {
                            Id = 14,
                            Amount = 1m,
                            DayOfWeek = "Вторник",
                            GoalTypeId = 1,
                            MealTimeId = 1,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 15,
                            Amount = 0.1m,
                            DayOfWeek = "Вторник",
                            GoalTypeId = 1,
                            MealTimeId = 1,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 16,
                            Amount = 2m,
                            DayOfWeek = "Вторник",
                            GoalTypeId = 1,
                            MealTimeId = 2,
                            ProductId = 20
                        },
                        new
                        {
                            Id = 17,
                            Amount = 0.1m,
                            DayOfWeek = "Вторник",
                            GoalTypeId = 1,
                            MealTimeId = 2,
                            ProductId = 31
                        },
                        new
                        {
                            Id = 18,
                            Amount = 2m,
                            DayOfWeek = "Вторник",
                            GoalTypeId = 1,
                            MealTimeId = 2,
                            ProductId = 21
                        },
                        new
                        {
                            Id = 19,
                            Amount = 1.5m,
                            DayOfWeek = "Вторник",
                            GoalTypeId = 1,
                            MealTimeId = 3,
                            ProductId = 36
                        },
                        new
                        {
                            Id = 20,
                            Amount = 1m,
                            DayOfWeek = "Вторник",
                            GoalTypeId = 1,
                            MealTimeId = 3,
                            ProductId = 37
                        },
                        new
                        {
                            Id = 21,
                            Amount = 0.3m,
                            DayOfWeek = "Вторник",
                            GoalTypeId = 1,
                            MealTimeId = 3,
                            ProductId = 46
                        },
                        new
                        {
                            Id = 22,
                            Amount = 1m,
                            DayOfWeek = "Вторник",
                            GoalTypeId = 1,
                            MealTimeId = 4,
                            ProductId = 32
                        },
                        new
                        {
                            Id = 23,
                            Amount = 1m,
                            DayOfWeek = "Вторник",
                            GoalTypeId = 1,
                            MealTimeId = 4,
                            ProductId = 13
                        },
                        new
                        {
                            Id = 24,
                            Amount = 1.5m,
                            DayOfWeek = "Вторник",
                            GoalTypeId = 1,
                            MealTimeId = 4,
                            ProductId = 17
                        },
                        new
                        {
                            Id = 25,
                            Amount = 1m,
                            DayOfWeek = "Вторник",
                            GoalTypeId = 1,
                            MealTimeId = 4,
                            ProductId = 28
                        },
                        new
                        {
                            Id = 26,
                            Amount = 2m,
                            DayOfWeek = "Среда",
                            GoalTypeId = 1,
                            MealTimeId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 27,
                            Amount = 1m,
                            DayOfWeek = "Среда",
                            GoalTypeId = 1,
                            MealTimeId = 1,
                            ProductId = 38
                        },
                        new
                        {
                            Id = 28,
                            Amount = 0.3m,
                            DayOfWeek = "Среда",
                            GoalTypeId = 1,
                            MealTimeId = 1,
                            ProductId = 46
                        },
                        new
                        {
                            Id = 29,
                            Amount = 0.15m,
                            DayOfWeek = "Среда",
                            GoalTypeId = 1,
                            MealTimeId = 2,
                            ProductId = 22
                        },
                        new
                        {
                            Id = 30,
                            Amount = 2m,
                            DayOfWeek = "Среда",
                            GoalTypeId = 1,
                            MealTimeId = 2,
                            ProductId = 42
                        },
                        new
                        {
                            Id = 31,
                            Amount = 0.1m,
                            DayOfWeek = "Среда",
                            GoalTypeId = 1,
                            MealTimeId = 2,
                            ProductId = 31
                        },
                        new
                        {
                            Id = 32,
                            Amount = 1.5m,
                            DayOfWeek = "Среда",
                            GoalTypeId = 1,
                            MealTimeId = 3,
                            ProductId = 11
                        },
                        new
                        {
                            Id = 33,
                            Amount = 1m,
                            DayOfWeek = "Среда",
                            GoalTypeId = 1,
                            MealTimeId = 3,
                            ProductId = 27
                        },
                        new
                        {
                            Id = 34,
                            Amount = 0.4m,
                            DayOfWeek = "Среда",
                            GoalTypeId = 1,
                            MealTimeId = 3,
                            ProductId = 12
                        },
                        new
                        {
                            Id = 35,
                            Amount = 0.5m,
                            DayOfWeek = "Среда",
                            GoalTypeId = 1,
                            MealTimeId = 4,
                            ProductId = 34
                        },
                        new
                        {
                            Id = 36,
                            Amount = 1.5m,
                            DayOfWeek = "Среда",
                            GoalTypeId = 1,
                            MealTimeId = 4,
                            ProductId = 39
                        },
                        new
                        {
                            Id = 37,
                            Amount = 0.15m,
                            DayOfWeek = "Среда",
                            GoalTypeId = 1,
                            MealTimeId = 4,
                            ProductId = 41
                        },
                        new
                        {
                            Id = 38,
                            Amount = 0.4m,
                            DayOfWeek = "Четверг",
                            GoalTypeId = 1,
                            MealTimeId = 1,
                            ProductId = 16
                        },
                        new
                        {
                            Id = 39,
                            Amount = 0.5m,
                            DayOfWeek = "Четверг",
                            GoalTypeId = 1,
                            MealTimeId = 1,
                            ProductId = 43
                        },
                        new
                        {
                            Id = 40,
                            Amount = 0.15m,
                            DayOfWeek = "Четверг",
                            GoalTypeId = 1,
                            MealTimeId = 1,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 41,
                            Amount = 2.0m,
                            DayOfWeek = "Четверг",
                            GoalTypeId = 1,
                            MealTimeId = 2,
                            ProductId = 44
                        },
                        new
                        {
                            Id = 42,
                            Amount = 0.5m,
                            DayOfWeek = "Четверг",
                            GoalTypeId = 1,
                            MealTimeId = 2,
                            ProductId = 19
                        },
                        new
                        {
                            Id = 43,
                            Amount = 1.5m,
                            DayOfWeek = "Четверг",
                            GoalTypeId = 1,
                            MealTimeId = 2,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 44,
                            Amount = 1.5m,
                            DayOfWeek = "Четверг",
                            GoalTypeId = 1,
                            MealTimeId = 3,
                            ProductId = 20
                        },
                        new
                        {
                            Id = 45,
                            Amount = 1.5m,
                            DayOfWeek = "Четверг",
                            GoalTypeId = 1,
                            MealTimeId = 3,
                            ProductId = 45
                        },
                        new
                        {
                            Id = 46,
                            Amount = 1.0m,
                            DayOfWeek = "Четверг",
                            GoalTypeId = 1,
                            MealTimeId = 4,
                            ProductId = 11
                        },
                        new
                        {
                            Id = 47,
                            Amount = 1.0m,
                            DayOfWeek = "Четверг",
                            GoalTypeId = 1,
                            MealTimeId = 4,
                            ProductId = 33
                        },
                        new
                        {
                            Id = 48,
                            Amount = 1.0m,
                            DayOfWeek = "Четверг",
                            GoalTypeId = 1,
                            MealTimeId = 4,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 49,
                            Amount = 0.1m,
                            DayOfWeek = "Четверг",
                            GoalTypeId = 1,
                            MealTimeId = 4,
                            ProductId = 12
                        },
                        new
                        {
                            Id = 50,
                            Amount = 2m,
                            DayOfWeek = "Пятница",
                            GoalTypeId = 1,
                            MealTimeId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 51,
                            Amount = 0.01m,
                            DayOfWeek = "Пятница",
                            GoalTypeId = 1,
                            MealTimeId = 1,
                            ProductId = 17
                        },
                        new
                        {
                            Id = 52,
                            Amount = 0.3m,
                            DayOfWeek = "Пятница",
                            GoalTypeId = 1,
                            MealTimeId = 1,
                            ProductId = 46
                        },
                        new
                        {
                            Id = 53,
                            Amount = 1.0m,
                            DayOfWeek = "Пятница",
                            GoalTypeId = 1,
                            MealTimeId = 1,
                            ProductId = 47
                        },
                        new
                        {
                            Id = 54,
                            Amount = 2.0m,
                            DayOfWeek = "Пятница",
                            GoalTypeId = 1,
                            MealTimeId = 2,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 55,
                            Amount = 1.5m,
                            DayOfWeek = "Пятница",
                            GoalTypeId = 1,
                            MealTimeId = 2,
                            ProductId = 49
                        },
                        new
                        {
                            Id = 56,
                            Amount = 0.1m,
                            DayOfWeek = "Пятница",
                            GoalTypeId = 1,
                            MealTimeId = 2,
                            ProductId = 31
                        },
                        new
                        {
                            Id = 57,
                            Amount = 1.5m,
                            DayOfWeek = "Пятница",
                            GoalTypeId = 1,
                            MealTimeId = 3,
                            ProductId = 14
                        },
                        new
                        {
                            Id = 58,
                            Amount = 1.0m,
                            DayOfWeek = "Пятница",
                            GoalTypeId = 1,
                            MealTimeId = 3,
                            ProductId = 27
                        },
                        new
                        {
                            Id = 59,
                            Amount = 0.15m,
                            DayOfWeek = "Пятница",
                            GoalTypeId = 1,
                            MealTimeId = 4,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 60,
                            Amount = 1.5m,
                            DayOfWeek = "Пятница",
                            GoalTypeId = 1,
                            MealTimeId = 4,
                            ProductId = 28
                        },
                        new
                        {
                            Id = 61,
                            Amount = 1.5m,
                            DayOfWeek = "Пятница",
                            GoalTypeId = 1,
                            MealTimeId = 4,
                            ProductId = 50
                        },
                        new
                        {
                            Id = 62,
                            Amount = 0.1m,
                            DayOfWeek = "Пятница",
                            GoalTypeId = 1,
                            MealTimeId = 4,
                            ProductId = 12
                        },
                        new
                        {
                            Id = 63,
                            Amount = 0.4m,
                            DayOfWeek = "Суббота",
                            GoalTypeId = 1,
                            MealTimeId = 1,
                            ProductId = 19
                        },
                        new
                        {
                            Id = 64,
                            Amount = 1m,
                            DayOfWeek = "Суббота",
                            GoalTypeId = 1,
                            MealTimeId = 1,
                            ProductId = 39
                        },
                        new
                        {
                            Id = 65,
                            Amount = 0.3m,
                            DayOfWeek = "Суббота",
                            GoalTypeId = 1,
                            MealTimeId = 1,
                            ProductId = 46
                        },
                        new
                        {
                            Id = 66,
                            Amount = 2m,
                            DayOfWeek = "Суббота",
                            GoalTypeId = 1,
                            MealTimeId = 2,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 67,
                            Amount = 2m,
                            DayOfWeek = "Суббота",
                            GoalTypeId = 1,
                            MealTimeId = 2,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 68,
                            Amount = 0.1m,
                            DayOfWeek = "Суббота",
                            GoalTypeId = 1,
                            MealTimeId = 2,
                            ProductId = 31
                        },
                        new
                        {
                            Id = 69,
                            Amount = 1.5m,
                            DayOfWeek = "Суббота",
                            GoalTypeId = 1,
                            MealTimeId = 3,
                            ProductId = 10
                        },
                        new
                        {
                            Id = 70,
                            Amount = 0.5m,
                            DayOfWeek = "Суббота",
                            GoalTypeId = 1,
                            MealTimeId = 3,
                            ProductId = 13
                        },
                        new
                        {
                            Id = 71,
                            Amount = 0.2m,
                            DayOfWeek = "Суббота",
                            GoalTypeId = 1,
                            MealTimeId = 4,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 72,
                            Amount = 1.5m,
                            DayOfWeek = "Суббота",
                            GoalTypeId = 1,
                            MealTimeId = 4,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 73,
                            Amount = 1m,
                            DayOfWeek = "Суббота",
                            GoalTypeId = 1,
                            MealTimeId = 4,
                            ProductId = 33
                        },
                        new
                        {
                            Id = 74,
                            Amount = 0.5m,
                            DayOfWeek = "Воскресенье",
                            GoalTypeId = 1,
                            MealTimeId = 1,
                            ProductId = 15
                        },
                        new
                        {
                            Id = 75,
                            Amount = 0.5m,
                            DayOfWeek = "Воскресенье",
                            GoalTypeId = 1,
                            MealTimeId = 1,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 76,
                            Amount = 1m,
                            DayOfWeek = "Воскресенье",
                            GoalTypeId = 1,
                            MealTimeId = 1,
                            ProductId = 47
                        },
                        new
                        {
                            Id = 77,
                            Amount = 0.15m,
                            DayOfWeek = "Воскресенье",
                            GoalTypeId = 1,
                            MealTimeId = 2,
                            ProductId = 22
                        },
                        new
                        {
                            Id = 78,
                            Amount = 2m,
                            DayOfWeek = "Воскресенье",
                            GoalTypeId = 1,
                            MealTimeId = 2,
                            ProductId = 42
                        },
                        new
                        {
                            Id = 79,
                            Amount = 0.1m,
                            DayOfWeek = "Воскресенье",
                            GoalTypeId = 1,
                            MealTimeId = 2,
                            ProductId = 31
                        },
                        new
                        {
                            Id = 80,
                            Amount = 1.5m,
                            DayOfWeek = "Воскресенье",
                            GoalTypeId = 1,
                            MealTimeId = 3,
                            ProductId = 14
                        },
                        new
                        {
                            Id = 81,
                            Amount = 1.5m,
                            DayOfWeek = "Воскресенье",
                            GoalTypeId = 1,
                            MealTimeId = 3,
                            ProductId = 45
                        },
                        new
                        {
                            Id = 82,
                            Amount = 0.1m,
                            DayOfWeek = "Воскресенье",
                            GoalTypeId = 1,
                            MealTimeId = 4,
                            ProductId = 12
                        },
                        new
                        {
                            Id = 83,
                            Amount = 1.5m,
                            DayOfWeek = "Воскресенье",
                            GoalTypeId = 1,
                            MealTimeId = 4,
                            ProductId = 17
                        },
                        new
                        {
                            Id = 84,
                            Amount = 1m,
                            DayOfWeek = "Воскресенье",
                            GoalTypeId = 1,
                            MealTimeId = 4,
                            ProductId = 28
                        });
                });

            modelBuilder.Entity("NutritionPlanner.DataAccess.Entities.ChatMessageEntity", b =>
                {
                    b.HasOne("NutritionPlanner.DataAccess.Entities.UserEntity", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NutritionPlanner.DataAccess.Entities.UserEntity", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("NutritionPlanner.DataAccess.Entities.MealPlanItemEntity", b =>
                {
                    b.HasOne("NutritionPlanner.DataAccess.Entities.MealPlanEntity", null)
                        .WithMany("MealPlanItems")
                        .HasForeignKey("MealPlanEntityId");
                });

            modelBuilder.Entity("NutritionPlanner.DataAccess.Entities.RecipeIngredientEntity", b =>
                {
                    b.HasOne("NutritionPlanner.DataAccess.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutritionPlanner.DataAccess.Entities.RecipeEntity", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("NutritionPlanner.DataAccess.Entities.MealPlanEntity", b =>
                {
                    b.Navigation("MealPlanItems");
                });

            modelBuilder.Entity("NutritionPlanner.DataAccess.Entities.RecipeEntity", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
